# 2024/jan/15 08:30:00 by RouterOS 7.14.3
# software id = DEMO-1234
#
# model = RB951Ui-2HnD
/interface bridge
add name=bridge1
/ip address
add address=192.168.88.1/24 interface=bridge1 network=192.168.88.0
/ip dns
set servers=8.8.8.8
/ip service
set telnet address=0.0.0.0/0
set ftp address=0.0.0.0/0
set www address=0.0.0.0/0
set ssh address=0.0.0.0/0
set api address=0.0.0.0/0
set winbox address=0.0.0.0/0
set api-ssl address=0.0.0.0/0
/ip ssh
set strong-crypto=no forwarding-enabled=no
/snmp
set enabled=yes
/snmp community
set [ find default=yes ] name=public addresses=0.0.0.0/0 security=none read-access=yes write-access=yes
/system identity
set name=MikroTik
/system note
set show-at-login=no
/tool bandwidth-server
set enabled=yes
/tool mac-server
set allowed-interface-list=all
/tool mac-server mac-winbox
set allowed-interface-list=all
/tool mac-server ping
set enabled=yes
/user
set [ find default=yes ] name=admin group=full
/user aaa
set use-radius=no
