! FastIron 09.0.10
hostname ICX-7150
clock timezone -300
ntp server 10.0.0.1
crypto key generate rsa
ip ssh
no telnet server
web-management https
no web-management http
enable password <SANITIZED_SECRET>
logging host 10.0.0.100