# ExtremeXOS version 31.7.1.3
configure snmp sysName EXOS-SW-01
configure timezone name EST -300 autodst
configure ntp server add 10.1.1.1
enable ssh2
disable telnet
disable web
enable web https
configure radius netlogin primary 10.1.1.100 client-ip 10.1.1.20 vr VR-Default
configure syslog add 10.1.1.50:514 vr VR-Default
configure banner before-login Authorized Access Only