# Fortinet FortiOS Hardened Reference Architecture
config system global
    set hostname "FGT-ENTERPRISE-HQ"
    set admintimeout 10
    set admin-sport 8443
    set admin-ssh-port 22
    set admin-https-redirect disable
    set strong-crypto enable
    set pre-login-banner enable
end

config system admin
    edit "secadmin"
        set accprofile "super_admin"
        set trusthost1 10.100.0.0 255.255.255.0
        set password <SANITIZED_SECRET>
    next
end

config system ntp
    set ntpserver "10.100.0.1"
    set type custom
    set syncinterval 60
end

config log syslogd setting
    set status enable
    set server "10.100.0.50"
    set mode udp
    set port 514
end

config firewall policy
    edit 1
        set name "Default-Deny-All"
        set srcintf "wan1"
        set dstintf "internal"
        set srcaddr "all"
        set dstaddr "all"
        set action deny
        set schedule "always"
        set service "ALL"
        set logtraffic all
    next
end
