# ==============================================================================
# SOURCE: Oxidized (https://github.com/ytti/oxidized)
# SOURCE FILE: spec/model/data/sonicos#snippets#simulation.yaml & lib/oxidized/model/sonicos.rb
# CLASSIFICATION: OXIDIZED_SIMULATION
# REAL DEVICE: NO (Simulation / Unit Test Fixture from GitHub issue #2699/#3339)
# VERSION: SonicOS 6.5.4.10-95n / SonicOS 7.x
# LICENSE: Apache-2.0 (Oxidized project)
# ==============================================================================
! # Example config line on NSA 4650 running SonicOS 6.5.4.10-95n from Issue #2699
system-uptime "1 Day, 23 Hours, 32 Minutes, 10 Seconds"
firmware-version SonicOS 6.5.4.10-95n
hostname NSA4650-OXIDIZED-SIM
administration
  web-management https-port 8443
  no web-management allow-http
  admin idle-timeout 10
  password-min-length 16
  password-complexity alphanumeric-symbolic
  exit
interface X0
  management https
  management ssh
  no management http
  no management snmp
  exit
snmp
  no snmp enable
  exit
log
  syslog-server 192.168.1.50 port 514 facility local0
  exit
ntp
  ntp-server 192.168.1.100
  ntp-server 192.168.1.101
  exit
end
