#scope:BoxAdministration
sys-name = "BarracudaFW01"
http-enable = "no"
https-enable = "yes"
ssh-enable = "yes"
timeout = "600"
dns-servers = "8.8.8.8,8.8.4.4"
ntp-servers = "pool.ntp.org"
logging-enabled = "yes"
logging-host = "192.168.1.100"