"""Deterministic SonicWall SonicOS CLI configuration parser.

This parser processes standard SonicOS text configuration files (generated by CLI exports),
normalizes verified security settings into the SecurityBaselineModel, and preserves
configuration lines and line numbers for compliance audit evidence.
"""

import hashlib
import re
from typing import Dict, List, Optional, Tuple

from ..models.baseline import ParserProvenance, SecurityBaselineModel, SnmpCommunity
from ..models.observation import Observation
from .base import ParserError, VendorParser, registry


@registry.register
class SonicWallSonicOSParser(VendorParser):
    """CLI-based configuration parser for SonicWall SonicOS."""

    name = "sonicwall_sonicos"
    vendor = "sonicwall"
    os_family = "sonicos"
    version = "1.0.0"
    base_confidence = 1.0

    @classmethod
    def detect(cls, config_text: str) -> float:
        if not config_text or not config_text.strip():
            return 0.0
        score = 0.0
        if "web-management " in config_text:
            score += 0.4
        if "idle-logout-time " in config_text:
            score += 0.4
        if "management ssh" in config_text or "management https" in config_text:
            score += 0.2
        if "dns-server primary" in config_text:
            score += 0.2
        return min(1.0, score)

    def parse(self, config_text: str, *, source_file: Optional[str] = None) -> SecurityBaselineModel:
        if not config_text or not config_text.strip():
            raise ParserError("Configuration is empty.")

        self._raw_lines = config_text.splitlines()
        
        baseline = SecurityBaselineModel(
            provenance=ParserProvenance(
                parser_name=self.name,
                parser_version=self.version,
                vendor=self.vendor,
                os_family=self.os_family,
                detection_confidence=self.detect(config_text),
            ),
            source_file=source_file,
            source_sha256=hashlib.sha256(config_text.encode("utf-8", errors="replace")).hexdigest(),
            config_line_count=len(self._raw_lines),
        )

        self._normalize_hostname(baseline)
        self._normalize_http_https(baseline)
        self._normalize_ssh_telnet(baseline)
        self._normalize_session_timeout(baseline)
        self._normalize_banner(baseline)
        self._normalize_dns(baseline)
        self._normalize_ntp(baseline)
        self._normalize_snmp(baseline)
        self._normalize_logging(baseline)

        # Set all remaining unparsed fields to unknown
        for field in baseline.observable_fields():
            observation = getattr(baseline, field)
            if observation.note == "Parser did not evaluate this field.":
                setattr(
                    baseline,
                    field,
                    type(observation).unknown(
                        "SonicOS parser does not evaluate this field."
                    )
                )

        return baseline

    def _evidence(self, line_num: int) -> Tuple[str, int, str]:
        raw_line = self._raw_lines[line_num - 1].strip()
        return raw_line, line_num, f"Line {line_num}: {raw_line}"

    def _find_line(self, pattern: re.Pattern) -> Optional[int]:
        """Find the 1-based line index matching the regex pattern."""
        for idx, line in enumerate(self._raw_lines):
            if pattern.search(line):
                return idx + 1
        return None

    def _normalize_hostname(self, baseline: SecurityBaselineModel) -> None:
        # Match 'hostname <name>' or 'system name <name>'
        pattern = re.compile(r'^\s*hostname\s+(\S+)', re.IGNORECASE)
        line_num = self._find_line(pattern)
        if line_num:
            match = pattern.search(self._raw_lines[line_num - 1])
            if match:
                hostname = match.group(1).strip()
                raw, line, note = self._evidence(line_num)
                baseline.hostname = Observation[str].found(hostname, raw, line, note=note)
                return
        baseline.hostname = Observation[str].unknown("Hostname is not configured in this CLI file.")

    def _normalize_http_https(self, baseline: SecurityBaselineModel) -> None:
        # HTTP Web Management
        http_allow_pat = re.compile(r'^\s*web-management\s+allow-http', re.IGNORECASE)
        http_deny_pat = re.compile(r'^\s*no\s+web-management\s+allow-http', re.IGNORECASE)

        allow_line = self._find_line(http_allow_pat)
        deny_line = self._find_line(http_deny_pat)

        if allow_line:
            raw, line, note = self._evidence(allow_line)
            baseline.http_server_enabled = Observation[bool].found(True, raw, line, note=note)
        elif deny_line:
            raw, line, note = self._evidence(deny_line)
            baseline.http_server_enabled = Observation[bool].found(False, raw, line, note=note)
        else:
            # Documented default: disabled
            baseline.http_server_enabled = Observation[bool].absent(
                False, "WebAdmin HTTP is disabled by default in SonicOS."
            )

        # HTTPS Web Management
        https_port_pat = re.compile(r'^\s*web-management\s+https-port\s+(\d+)', re.IGNORECASE)
        port_line = self._find_line(https_port_pat)

        if port_line:
            raw, line, note = self._evidence(port_line)
            baseline.https_server_enabled = Observation[bool].found(True, raw, line, note=note)
        else:
            # Documented default: enabled
            baseline.https_server_enabled = Observation[bool].absent(
                True, "WebAdmin HTTPS is enabled by default in SonicOS."
            )

    def _normalize_ssh_telnet(self, baseline: SecurityBaselineModel) -> None:
        # Telnet is unsupported/disabled on modern SonicOS by default
        baseline.telnet_enabled = Observation[bool].absent(
            False, "Telnet is unsupported for admin management in modern SonicOS."
        )

        # SSH Management settings
        ssh_enable_pat = re.compile(r'^\s*management\s+ssh', re.IGNORECASE)
        ssh_disable_pat = re.compile(r'^\s*no\s+management\s+ssh', re.IGNORECASE)

        enable_line = self._find_line(ssh_enable_pat)
        disable_line = self._find_line(ssh_disable_pat)

        if enable_line:
            raw, line, note = self._evidence(enable_line)
            baseline.ssh_enabled = Observation[bool].found(True, raw, line, note=note)
            baseline.vty_transport_input = Observation[List[str]].found(["ssh"], raw, line, note=note)
        elif disable_line:
            raw, line, note = self._evidence(disable_line)
            baseline.ssh_enabled = Observation[bool].found(False, raw, line, note=note)
            baseline.vty_transport_input = Observation[List[str]].found([], raw, line, note=note)
        else:
            # Default SSH: Return unknown because interface-level permissions vary
            baseline.ssh_enabled = Observation[bool].unknown(
                "SSH interface-level status is not explicitly set in configuration."
            )
            baseline.vty_transport_input = Observation[List[str]].unknown(
                "VTY allowed transports are not explicitly set in configuration."
            )

        baseline.ssh_version = Observation[int].unknown(
            "SSH protocol version is not configurable in standard SonicOS CLI."
        )

    def _normalize_session_timeout(self, baseline: SecurityBaselineModel) -> None:
        # idle-logout-time is in minutes
        timeout_pat = re.compile(r'^\s*idle-logout-time\s+(\d+)', re.IGNORECASE)
        line_num = self._find_line(timeout_pat)

        if line_num:
            match = timeout_pat.search(self._raw_lines[line_num - 1])
            if match:
                minutes = int(match.group(1))
                raw, line, note = self._evidence(line_num)
                baseline.vty_exec_timeout_seconds = Observation[int].found(
                    minutes * 60, raw, line, note=note
                )
                return
        # Documented default: 15 minutes (900 seconds)
        baseline.vty_exec_timeout_seconds = Observation[int].absent(
            900, "Idle logout time defaults to 15 minutes."
        )

    def _normalize_banner(self, baseline: SecurityBaselineModel) -> None:
        # disclaimers/login disclaimer text
        banner_pat = re.compile(r'^\s*disclaimer\s+enable', re.IGNORECASE)
        line_num = self._find_line(banner_pat)
        if line_num:
            raw, line, note = self._evidence(line_num)
            baseline.login_banner_present = Observation[bool].found(True, raw, line, note=note)
            return

        baseline.login_banner_present = Observation[bool].unknown(
            "Login disclaimer/banner status is not defined in configuration."
        )

    def _normalize_dns(self, baseline: SecurityBaselineModel) -> None:
        primary_pat = re.compile(r'^\s*dns-server\s+primary\s+(\S+)', re.IGNORECASE)
        secondary_pat = re.compile(r'^\s*dns-server\s+secondary\s+(\S+)', re.IGNORECASE)

        pri_line = self._find_line(primary_pat)
        sec_line = self._find_line(secondary_pat)

        servers = []
        line_num = None

        if pri_line:
            match = primary_pat.search(self._raw_lines[pri_line - 1])
            if match:
                servers.append(match.group(1).strip())
                line_num = pri_line
        if sec_line:
            match = secondary_pat.search(self._raw_lines[sec_line - 1])
            if match:
                servers.append(match.group(1).strip())
                if not line_num:
                    line_num = sec_line

        if servers and line_num:
            raw, line, note = self._evidence(line_num)
            baseline.dns_servers = Observation[List[str]].found(servers, raw, line, note=note)
        else:
            baseline.dns_servers = Observation[List[str]].unknown(
                "DNS servers are not explicitly configured in this CLI file."
            )

    def _normalize_ntp(self, baseline: SecurityBaselineModel) -> None:
        # Match 'ntp-server <ip>' or 'ntp server <ip>'
        ntp_pat = re.compile(r'^\s*ntp-server\s+(\S+)', re.IGNORECASE)
        line_num = self._find_line(ntp_pat)

        if line_num:
            match = ntp_pat.search(self._raw_lines[line_num - 1])
            if match:
                server = match.group(1).strip()
                raw, line, note = self._evidence(line_num)
                baseline.ntp_servers = Observation[List[str]].found([server], raw, line, note=note)
                return

        baseline.ntp_servers = Observation[List[str]].unknown(
            "NTP servers are not explicitly configured in this CLI file."
        )

    def _normalize_snmp(self, baseline: SecurityBaselineModel) -> None:
        # Match SNMP community configurations
        snmp_comm_pat = re.compile(r'^\s*snmp-server\s+community\s+(\S+)', re.IGNORECASE)
        line_num = self._find_line(snmp_comm_pat)

        communities = []
        if line_num:
            for idx, line in enumerate(self._raw_lines):
                match = snmp_comm_pat.search(line)
                if match:
                    comm_name = match.group(1).strip()
                    communities.append(
                        SnmpCommunity(
                            name=comm_name,
                            access="ro",  # Default read-only community access in CLI configurations
                            acl=None,
                            source_line=line.strip(),
                            line_number=idx + 1
                        )
                    )

        if communities:
            lines_str = "\n".join(c.source_line for c in communities)
            baseline.snmp_communities = Observation[List[SnmpCommunity]].found(
                communities, lines_str, communities[0].line_number
            )
        else:
            baseline.snmp_communities = Observation[List[SnmpCommunity]].unknown(
                "SNMP community configurations are not present in this CLI file."
            )

    def _normalize_logging(self, baseline: SecurityBaselineModel) -> None:
        # Match syslog servers or reporting servers
        syslog_pat = re.compile(r'^\s*syslog-server\s+(\S+)', re.IGNORECASE)
        line_num = self._find_line(syslog_pat)

        if line_num:
            match = syslog_pat.search(self._raw_lines[line_num - 1])
            if match:
                server = match.group(1).strip()
                raw, line, note = self._evidence(line_num)
                baseline.logging_enabled = Observation[bool].found(True, raw, line, note=note)
                baseline.logging_hosts = Observation[List[str]].found([server], raw, line, note=note)
                return

        baseline.logging_enabled = Observation[bool].unknown(
            "Syslog destinations are not configured in this CLI file."
        )
        baseline.logging_hosts = Observation[List[str]].unknown(
            "Syslog server destinations are not configured in this CLI file."
        )
