# Cumulus Linux FRRouting Configuration
hostname cumulus-leaf01
log syslog informational
service password-encryption
!
line vty
 exec-timeout 10 0
!
router bgp 65101
 bgp router-id 10.0.0.1
 neighbor FABRIC peer-group
 neighbor FABRIC remote-as 65000
 neighbor FABRIC password 8 $8$SanitizedBGPPwdHash...
!
