!
hostname new_router
!
enable secret 5 $1$mERr$hx5RL
enable password legacy_cleartext_pwd
!
no service password-encryption
!
username root privilege 15 secret 5 $1$mERr$hx5RL
!
line vty 0 4
 transport input telnet ssh
 exec-timeout 30 0
!
ip ssh version 1
!
ip http server
no ip http secure-server
!
banner login ^C
Unauthorized use is permitted under certain guidelines.
^C
!
snmp-server community public RW
snmp-server community private RW
!
no logging on
!
ntp server 192.168.99.1
!
end
