# TiMOS-B-22.10.R1 SR OS Configuration
configure {
    system {
        name "Nokia-7750-SR"
        time {
            ntp {
                server 10.0.0.1
            }
        }
        security {
            telnet {
                shutdown true
            }
            ssh {
                server {
                    shutdown false
                }
            }
            password {
                complexity true
                minimum-length 14
            }
        }
        log {
            syslog {
                server 10.0.0.100
            }
        }
    }
}