!Software Version V200R010C00SPC600
#
sysname INSECURE-VRP
#
undo info-center enable
#
telnet server enable
#
http server enable
undo http secure-server enable
#
super password simple insecure_super
#
aaa
 local-user netops password simple insecure123
 local-user netops privilege level 15
 local-user netops service-type ssh terminal telnet
#
snmp-agent
snmp-agent community read simple public
snmp-agent community write simple private
#
user-interface con 0
 authentication-mode aaa
user-interface vty 0 4
 authentication-mode aaa
 idle-timeout 0
#
return
