/* EdgeOS v2.0.9 */
system {
    host-name EdgeRouter-01
    time-zone UTC
    ntp {
        server 10.0.0.1
    }
    service {
        ssh {
            protocol-version v2
            port 22
        }
        gui {
            https-port 443
            http-port 0
        }
        telnet {
            disable
        }
    }
    syslog {
        host 10.0.0.100 {
            facility all {
                level notice
            }
        }
    }
}