!Software Version V200R010C00SPC600
#
sysname SECURE-VRP
#
clock timezone IST add 05:30:00
#
info-center enable
info-center loghost 10.30.40.50
#
undo telnet server enable
stelnet server enable
#
undo http server enable
http secure-server enable
#
super password irreversible-cipher @%^Hy7Kd2Lm9Pq_SUPER
#
aaa
 local-user netops password irreversible-cipher @%^Hy7Kd2Lm9Pq
 local-user netops privilege level 15
 local-user netops service-type ssh terminal
#
ssh user netops authentication-type password
ssh user netops service-type stelnet
ssh server version 2
ssh server compatible-ssh1x disable
#
snmp-agent
snmp-agent community read cipher %#Zx4Vb8Nm1Qw#% acl 2000
snmp-agent sys-info version v3
#
ntp-service unicast-server 10.30.40.41
#
header login information "authorized users only"
#
acl 2000
 rule permit source 10.30.40.0 0.0.0.255
 rule deny
#
user-interface con 0
 authentication-mode aaa
user-interface vty 0 4
 authentication-mode aaa
 protocol inbound ssh
 idle-timeout 10 0
 acl 2000 inbound
#
return
